### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by cziesman** [Alfresco/spring-social-salesforce#4]
Can you clarify the license for this project? Spring Social uses Apache 2.0.

**Comment by jottley** [comment]
Apache 2.0 would be our assumption of the license.  We have forked it from a fork of the original project, as have many others.  There has been no clarification of the license from the project founder (https://github.com/bdill/spring-social-salesforce/issues/6). I'm not sure if we can place a license on the file...but if we did it would be Apache 2.0
